export const header: string;
export const backgroundWrapper: string;
export const h1: string;
export const h3: string;
export const headerContent: string;
export const headerShape: string;
export const nav: string;
export const scrollactiveItem: string;
export const isActive: string;
