import { Asset, Entry } from 'contentful';

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

export interface IPostFields {
    /** Slug */
    slug?: string | undefined;

    /** Headline */
    headline: string | undefined;

    /** Description */
    description?: string | undefined;

    /** Date modified */
    dateModified?: string | undefined;

    /** Image */
    image: Asset | undefined;

    /** Article body */
    articleBody?: string | undefined;
}

export interface IPost extends Entry<IPostFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'post';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

type CONTENT_TYPE = 'post';

type LOCALE_CODE = 'de';

type CONTENTFUL_DEFAULT_LOCALE_CODE = 'de';
