/** Declaration file generated by dts-gen */

export function hydrateOnInteraction(component: any, ...args: any[]): any;

export function hydrateSsrOnly(component: any): any;

export function hydrateWhenIdle(component: any, ...args: any[]): any;

export function hydrateWhenVisible(component: any, ...args: any[]): any;


